export const SUPPORT_CASE_MAX_REASON_LENGTH = 2000;
export const SUPPORT_CASE_MAX_DESCRIPTION_LENGTH = 5000;
export const SUPPORT_CASE_MAX_RESOLUTION_CODE_LENGTH = 128;
export const SUPPORT_CASE_MAX_RESOLUTION_REASON_LENGTH = 2000;
export const SUPPORT_CASE_MAX_EVIDENCE_REFS = 20;
export const SUPPORT_CASE_MAX_EVIDENCE_REF_LENGTH = 512;
export const SUPPORT_CASE_MAX_SEARCH_LENGTH = 200;
